### ISSUE TITLE
Walk selection set when writing, rather than payload

### ISSUE THREAD

**Issue by nevir** [convoyinc/apollo-cache-hermes#115]
Currently, we [walk the payload](https://github.com/convoyinc/apollo-cache-hermes/blob/master/src/util/tree.ts#L61) when merges values into the cache.  This leads to ambiguity [and hacky situations](https://github.com/convoyinc/apollo-cache-hermes/blob/master/src/operations/SnapshotEditor.ts#L278-L281) where we can't know whether a value should be placed directly in the cache, or walked - particularly for fields that contain complex objects

**Comment by yuit** [comment]
I believe this is done by PR #120
