### ISSUE TITLE
Support for readFragment & writeFragment

### ISSUE THREAD

**Issue by jchavarri** [convoyinc/apollo-cache-hermes#151]
I'm trying Apollo 2.0, and didn't see much performance improvements using the default in-memory cache, in some cases it's actually worse than the Redux based version. I'm testing with pages that have 1000+ objects (or nodes, in Hermes terminology), so I decided to try with Hermes, as it seems to be fastest that any GraphQL cache out there.

When testing `0.3.0-alpha` (and `apollo-client` `2.0.0-beta.4`) I get the following error:

```
TypeError: this.dataStore.getCache(...).transformDocument is not a function
    at QueryManager.fetchQuery
    at QueryManager.startQuery
    at ObservableQuery.setUpQuery
    at ObservableQuery.onSubscribe
    at new Subscription
    at ObservableQuery.Observable.subscribe
    at Expansion._this.subscribeToQuery
    at Expansion._this.handleQuery
    at Expansion._this.updateWrapperQuery
```

This is how I'm creating the client. Note I'm using `dataIdFromObject` and an auth link:

```js
...
import { Cache as HermesCache } from 'apollo-cache-hermes';

export const createApolloClient = ({
  databaseId,
  previewKey,
  uri = `/api/v1/databases/${databaseId}/apollo?preview=${previewKey}`,
  ssrMode = false,
}) => {
  ...

  return new ApolloClient({
    link,
    cache: new HermesCache({
      dataIdFromObject: object => object.id
    }),
    ssrMode,
  });
};
```

Is there anything else I should do to make the Hermes cache work?

**Comment by jchavarri** [comment]
Hm.. i understand a bit better now. It seems what I should import is `Hermes`, as that's the interface to Apollo.

If I `import { Hermes as HermesCache } from 'apollo-cache-hermes';` I get the following error:

```
WebflowFlux.bundle.js:553606 Uncaught Error: GraphQL document is missing an operation
    at Object.getOperationDefinitionOrDie [as getOperationOrDie]
    at new QueryInfo
    at CacheContext._queryInfo
    at CacheContext.parseQuery
    at Object.read
    at Cache.read
    at Hermes.ApolloQueryable.readFragment
    at ApolloClient.readFragment
    at Expansion._this.handleQuery
    at Expansion._this.updateBindingAndConditionQuery
```

When trying to read some fragments. I saw nested fragments are not supported yet, but I'm querying a regular fragment:
```
fragment BindingOrCondition_15ee809e_afdd_e02d_f495_f2d7fd0e9ed8 on Dynamo {
  id f_slug_ f_shoot_type_5dr {
    f_name_ id
    f__draft_0ht
    f__archived_0ht
  }
  f_location_ {
    f_name_ id
    f__draft_0ht
    f__archived_0ht
  }
}
```

Seems the query is missing an `OperationDefinition`, it only has `FragmentDefinition`. I can try and contribute a fix for this, if you have some pointers to where I should look at :)

**Comment by nevir** [comment]
Ah!  Yeah, I haven't had a chance to fill in support for reading fragments yet :(

If you want to poke around, the entry point is https://github.com/convoyinc/apollo-cache-hermes/blob/master/src/apollo/Queryable.ts#L49

The code that's emitting the error is https://github.com/convoyinc/apollo-cache-hermes/blob/master/src/context/CacheContext.ts#L119-L156

The short of it is that `CacheContext` will need another method (or modification to `parseOperation`) to support fragments.  Ultimately, it needs to be able to convert from the GraphQL AST document w/ a fragment into a [`ParsedQuery`](https://github.com/convoyinc/apollo-cache-hermes/blob/master/src/schema.ts#L56)

**Comment by nevir** [comment]
As a workaround - if it's feasible - convert those readFragment calls into reads

**Comment by nevir** [comment]
👍 this is in
