### ISSUE TITLE
Are there any docs?

### ISSUE THREAD

**Issue by helfer** [convoyinc/apollo-cache-hermes#194]
Hey guys, I'm really curious to see how your store performs compared with the InMemoryStore, especially when making several mutations per second and stacking a few hundred or a couple thousand optimistic updates before resolving them. However, there's very little documentation for this package and not even really a readme that tells me how to use it, and what to expect. For example, can I just plug it in place of the InMemoryStore with the same arguments (dataIdFromObject, addTypename being the most important ones) and expect everything to work, including readFragment and writeFragment? Or are there certain things that are different, things that haven't been implemented yet, etc.?

Btw, I looked into the source code to figure things out, but I still couldn't get it to work in Typescript because of missing exports and compiler issues (skipLibCheck didn't help). Are you actually using the package you published or are you using a local version?

**Comment by nevir** [comment]
Currently working on documenting it; in the meantime, your best bet is probably to dig into the configuration options: https://github.com/convoyinc/apollo-cache-hermes/blob/master/src/context/CacheContext.ts#L58-L116 - also the conceptual docs may help too (albeit are pretty verbose): https://github.com/convoyinc/apollo-cache-hermes/tree/master/docs

No support for readFragment/writeFragment yet - see #151 for that

We're using the published version; though the projects we're using it in are not TS :( - which exports are missing when you try to pull it in?

**Comment by nevir** [comment]
Updated the readme - does that clarify things?

**Comment by helfer** [comment]
Thanks a lot @nevir, and sorry I didn't see this again until now. I started experimenting with building my own store instead 😬
