### ISSUE TITLE
feature request: allow GQL queries with InlineFragment

### ISSUE THREAD

**Issue by finnigantime** [convoyinc/apollo-cache-hermes#274]
**Summary**:
I'm trying to do:
<img width="329" alt="screen shot 2017-12-27 at 5 23 34 pm" src="https://user-images.githubusercontent.com/1305608/34397414-cb82713c-eb2a-11e7-9a67-a868da27a7d7.png">

**Expected Behavior**:
Able to use inline GQL fragments. The above query works fine in `GraphiQL`.

**Actual Behavior**:
I get this error:
<img width="683" alt="screen shot 2017-12-27 at 5 23 39 pm" src="https://user-images.githubusercontent.com/1305608/34397418-cdb7013e-eb2a-11e7-9aed-f78f56422c98.png">

**Comment by finnigantime** [comment]
From chatting with @nevir - this is support we should add. Parameterized queries make this tough. For the initial stab, we could thrown an error if you try to use parameterized queries within InlineFragments. apollo-cache-hermes could treat members of InlineFragments as optional fields when reading/writing (or perhaps go off `__typename`).

**Comment by nevir** [comment]
Let's merge this into #153 too
