### ISSUE TITLE
Complete fix for greenkeeper's lockfile support

### ISSUE THREAD

**Issue by nevir** [convoyinc/apollo-cache-hermes#316]
Waiting on https://github.com/greenkeeperio/greenkeeper-lockfile/pull/118 - let's get off of our fork

**Comment by patkub** [comment]
@nevir with https://github.com/greenkeeperio/greenkeeper-lockfile/pull/167 greenkeeper-lockfile@2 now supports CircleCI workflows. Run greenkeeper-lockfile-update in the first job, and greenkeeper-lockfile-upload in any job (ideally the last job).
