### ISSUE TITLE
Support freezeResults?

### ISSUE THREAD

**Issue by wmertens** [convoyinc/apollo-cache-hermes#420]
I can't find `freezeResults` ([supported by apollo-cache-inmemory](https://blog.apollographql.com/whats-new-in-apollo-client-2-6-b3acf28ecad1)) in the repo, and it's been useful to catch dev errors in the past.

Are objects frozen by default, or would this be a useful addition?

**Comment by nevir** [comment]
Hermes defaults to freezing objects as long as `NODE_ENV !== 'production'` (this used to be inmemory's original behavior, as well; not sure if it still has the same default). You can control that via the [`freeze` configuration option](https://github.com/convoyinc/apollo-cache-hermes/blob/master/src/context/CacheContext.ts#L81-L86)

**Comment by wmertens** [comment]
Great 👍
