### ISSUE TITLE
Cache redirects

### ISSUE THREAD

**Issue by nevir** [convoyinc/apollo-cache-hermes#47]
Need to support cache redirects.

Motivation is to support queries like:

```graphql
query getAUser($id: ID!) {
  user(id: $id) { ... }
}
```

and return the entity with that id, no matter where it was retrieved from

**Comment by yuit** [comment]
While we are at it, we should consider customResolver similar to the one in Apollo-in-memory-cache

**Comment by nevir** [comment]
design doc: https://docs.google.com/document/d/1x2tQWTJbchfoU8i56NTxwsnqnpDJMQvPVKQ5JiHbSco/
